### ISSUE TITLE
Implement Error Codes

### ISSUE THREAD

**Issue by qdot** [metafetish/buttplug#20]
The Error Message should have an error code field, with a standardized set of errors set out in the spec. This means we can relay things like ping timeouts without having to create new messages.

- [x] metafetish/buttplug-js#3
- [x] metafetish/buttplug-csharp#95
- [x] metafetish/buttplug-csharp#96
- [x] metafetish/buttplug#19
